### ISSUE TITLE
What's the plan?

### ISSUE THREAD

**Issue by klimashkin** [lodash/webpack-plugin-lodash#1]
Finally!
So you want to use es6 version of lodash and webpack's tree-shaking?
Or some manual approach?

**Comment by jdalton** [comment]
The plan is to add sugar around the [`NormalModuleReplacementPlugin` plugin use](https://gist.github.com/jdalton/7f71e4590ec1202a36c1e3f836d758e2).

Something like:
* Level 1 would remove iteratee shorthand sugar
* Level 2 would remove metadata deps (disabling curry) but making the deps of `bind` and `partial` lighter.

This would be something you could use in combination with [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash).

**Comment by robcolburn** [comment]
@jdalton first link is dead 💔 , though it appears your 19 day is accomplished?

**Comment by jdalton** [comment]
>  first link is dead :broken_heart: , though it appears your 19 day roadmap is accomplished?

Thanks, I removed the link. Yep, roadmap so far has been accomplished.

**Comment by jdalton** [comment]
I'm on the lookout for more saving and feature sets.
